#!/bin/bash

# Seat Secure - Complete Setup Script

echo "🎬 SeatSecure Setup Guide"
echo "=========================="
echo ""
echo "Your MongoDB cluster is configured at:"
echo "ac-ocikp8f-shard-00-02.gnnxctj.mongodb.net"
echo ""
echo "IMPORTANT: You need to provide your MongoDB credentials"
echo ""
echo "Step 1: Open MongoDB Atlas"
echo "  → Go to https://cloud.mongodb.com"
echo "  → Find your cluster (ac-ocikp8f)"
echo "  → Click 'Database Access' on the left"
echo "  → Add a database user (save username and password)"
echo "  → Click 'Network Access' and add IP 0.0.0.0/0 (for dev)"
echo ""
echo "Step 2: Edit the .env file"
echo "  → Open: backend/.env"
echo "  → Replace <username> with your MongoDB user"
echo "  → Replace <password> with your MongoDB password"
echo "  → Save the file"
echo ""
echo "Step 3: Run the seed script"
echo "  → cd backend"
echo "  → npm run seed"
echo ""
echo "Step 4: Start the servers"
echo "  → Terminal 1: cd backend && npm run start:dev"
echo "  → Terminal 2: npm run dev"
echo ""
echo "Step 5: Test the system"
echo "  → Open: http://localhost:8080"
echo "  → Login with: student@college.edu / Student@123"
echo ""
echo "Questions?"
echo "  → Check MONGODB_SETUP.md for detailed instructions"
echo "  → Check QUICK_START.md for quick reference"
echo "  → Check COMPLETE_GUIDE.md for full documentation"
echo ""
